import React, { useEffect, useState } from 'react';
import { fetchWithAuth } from '../../shared/lib/authInterceptor';

type Shift = { id: string; business_date: string; day_start: string; status: string; opening_float: string; expected_cash: string; actual_cash: string | null; difference: string | null };
type Settings = { day_start: string; day_end: string; timezone: string | null };
type FinanceEntry = { id: string; shift_id: string; business_date: string; status: 'PENDING_REVIEW' | 'CONFIRMED' | 'REJECTED'; expected_cash: string; actual_cash: string | null; difference: string | null; confirmed_at: string | null; rejected_reason: string | null };
type Tab = 'ACTIVE' | 'HISTORY' | 'FINANCE' | 'SETTINGS';

const money = (value: string | null) => value === null ? '—' : Number(value).toFixed(2);
async function json(response: Response) { const body = await response.json(); if (!response.ok) throw new Error(body.error || 'SHIFT_REQUEST_FAILED'); return body; }

export const ShiftDashboard: React.FC = () => {
  const [tab, setTab] = useState<Tab>('ACTIVE'); const [active, setActive] = useState<Shift | null>(null); const [history, setHistory] = useState<Shift[]>([]); const [financeEntries, setFinanceEntries] = useState<FinanceEntry[]>([]);
  const [settings, setSettings] = useState<Settings>({ day_start: '11:00', day_end: '01:00', timezone: 'Asia/Karachi' });
  const [opening, setOpening] = useState('0.00'); const [actual, setActual] = useState('0.00'); const [terminal, setTerminal] = useState(''); const [notes, setNotes] = useState(''); const [rejectionReason, setRejectionReason] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = async () => { try { const [a, h, s, f] = await Promise.all([fetchWithAuth('/api/shifts/active').then(json), fetchWithAuth('/api/shifts').then(json), fetchWithAuth('/api/shifts/settings').then(json), fetchWithAuth('/api/cashier/finance/report').then(json)]); setActive(a.shift); setHistory(h.shifts); setSettings(s.settings); setFinanceEntries(f.entries); } catch (e: any) { setError(e.message || 'Unable to load shifts.'); } };
  useEffect(() => { void refresh(); }, []);
  const submit = async (url: string, body: Record<string, unknown>) => { setBusy(true); setError(''); try { await fetchWithAuth(url, { method: url.endsWith('settings') ? 'PATCH' : 'POST', body: JSON.stringify(body) }).then(json); await refresh(); } catch (e: any) { setError(e.message || 'Unable to save shift.'); } finally { setBusy(false); } };
  return <section className="p-6 max-w-6xl mx-auto space-y-5"><div><h2 className="text-2xl font-bold text-white">Shift control</h2><p className="text-sm text-slate-400">Restaurant-level cash reconciliation by business date.</p></div><div className="flex gap-2 border-b border-slate-800">{(['ACTIVE', 'HISTORY', 'FINANCE', 'SETTINGS'] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`px-4 py-2 text-sm font-semibold ${tab === item ? 'text-gold-500 border-b-2 border-gold-500' : 'text-slate-400'}`}>{item[0] + item.slice(1).toLowerCase()}</button>)}</div>{error && <p className="p-3 text-sm text-red-200 border border-red-500/30 rounded bg-red-500/10">{error}</p>}
    {tab === 'ACTIVE' && <div className="p-5 space-y-4 rounded-xl border border-slate-800 bg-slate-900/50">{active ? <><div><strong className="text-green-400">Open shift</strong><p className="text-sm text-slate-400">Business date {active.business_date.slice(0, 10)} · opening float {money(active.opening_float)}</p></div><div className="grid md:grid-cols-3 gap-3"><input value={actual} onChange={(e) => setActual(e.target.value)} inputMode="decimal" placeholder="Actual cash" className="p-2 rounded bg-slate-950 border border-slate-700" /><input value={terminal} onChange={(e) => setTerminal(e.target.value)} placeholder="Terminal ID" className="p-2 rounded bg-slate-950 border border-slate-700" /><input value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Close notes" className="p-2 rounded bg-slate-950 border border-slate-700" /></div><button disabled={busy} onClick={() => void submit('/api/shifts/close', { shift_id: active.id, actual_cash: actual, terminal_id: terminal, notes })} className="px-4 py-2 rounded bg-red-600 text-white disabled:opacity-50">Close shift</button></> : <><p className="text-slate-400">No shift is open for the current business date.</p><div className="grid md:grid-cols-2 gap-3"><input value={opening} onChange={(e) => setOpening(e.target.value)} inputMode="decimal" placeholder="Opening float" className="p-2 rounded bg-slate-950 border border-slate-700" /><input value={terminal} onChange={(e) => setTerminal(e.target.value)} placeholder="Terminal ID" className="p-2 rounded bg-slate-950 border border-slate-700" /></div><button disabled={busy} onClick={() => void submit('/api/shifts/open', { opening_float: opening, terminal_id: terminal })} className="px-4 py-2 rounded bg-gold-500 text-black disabled:opacity-50">Open shift</button></>}</div>}
    {tab === 'HISTORY' && <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="min-w-full text-sm"><thead className="text-left text-slate-400 bg-slate-900"><tr><th className="p-3">Business date</th><th>Opened</th><th>Status</th><th>Expected</th><th>Actual</th><th>Difference</th></tr></thead><tbody>{history.map((shift) => <tr key={shift.id} className="border-t border-slate-800"><td className="p-3">{shift.business_date.slice(0, 10)}</td><td>{new Date(shift.day_start).toLocaleString()}</td><td>{shift.status}</td><td>{money(shift.expected_cash)}</td><td>{money(shift.actual_cash)}</td><td>{money(shift.difference)}</td></tr>)}</tbody></table></div>}
    {tab === 'FINANCE' && <div className="space-y-3"><input value={rejectionReason} onChange={(e) => setRejectionReason(e.target.value)} placeholder="Reason required when rejecting an entry" className="w-full max-w-xl p-2 rounded bg-slate-950 border border-slate-700" />{financeEntries.map((entry) => <div key={entry.id} className="p-4 rounded-xl border border-slate-800 bg-slate-900/50 flex flex-wrap items-center gap-3"><div className="mr-auto"><strong>{entry.business_date.slice(0, 10)}</strong><span className="ml-3 text-sm text-slate-400">{entry.status} · Expected {money(entry.expected_cash)} · Actual {money(entry.actual_cash)}</span>{entry.confirmed_at && <span className="block text-xs text-green-400">Confirmed {new Date(entry.confirmed_at).toLocaleString()}</span>}{entry.rejected_reason && <span className="block text-xs text-red-300">Rejected: {entry.rejected_reason}</span>}</div>{entry.status === 'PENDING_REVIEW' && <><button disabled={busy} onClick={() => void submit('/api/cashier/finance/confirm', { finance_entry_id: entry.id })} className="px-3 py-2 rounded bg-green-600 text-white disabled:opacity-50">Confirm</button><button disabled={busy || !rejectionReason.trim()} onClick={() => void submit('/api/cashier/finance/reject', { finance_entry_id: entry.id, reason: rejectionReason })} className="px-3 py-2 rounded bg-red-600 text-white disabled:opacity-50">Reject</button></>}</div>)}{history.filter((shift) => shift.status === 'CLOSED' && !financeEntries.some((entry) => entry.shift_id === shift.id)).map((shift) => <button key={shift.id} disabled={busy} onClick={() => void submit('/api/cashier/finance/entry', { shift_id: shift.id })} className="mr-2 px-3 py-2 rounded border border-gold-500 text-gold-500 disabled:opacity-50">Create finance review for {shift.business_date.slice(0, 10)}</button>)}</div>}
    {tab === 'SETTINGS' && <div className="p-5 space-y-4 rounded-xl border border-slate-800 bg-slate-900/50 max-w-xl"><p className="text-sm text-slate-400">Boundaries use {settings.timezone || 'Asia/Karachi'} restaurant-local time.</p><div className="grid grid-cols-2 gap-3"><label>Day start<input type="time" value={settings.day_start} onChange={(e) => setSettings({ ...settings, day_start: e.target.value })} className="mt-1 block w-full p-2 rounded bg-slate-950 border border-slate-700" /></label><label>Day end<input type="time" value={settings.day_end} onChange={(e) => setSettings({ ...settings, day_end: e.target.value })} className="mt-1 block w-full p-2 rounded bg-slate-950 border border-slate-700" /></label></div><button disabled={busy} onClick={() => void submit('/api/shifts/settings', settings)} className="px-4 py-2 rounded bg-gold-500 text-black disabled:opacity-50">Save boundaries</button></div>}
  </section>;
};
