import { fetchWithAuth } from './src/shared/lib/authInterceptor';

async function testSettle() {
  console.log("Fetching orders...");
  const res = await fetch('http://localhost:3001/api/orders', { headers: { 'Authorization': 'Bearer test' } });
  // Just want to see what headers are generated by authInterceptor if we mock it?
}
testSettle();
